### ISSUE TITLE
Show PBs Only Button Uncollapses Subsplits

### ISSUE THREAD

**Issue by AJ213** [noahkra/SplitsAnalyser#11]
**Describe the bug**
If you collapse your splits, hitting the "Show PBs Only" button will uncollapse them aka not saving the collapsed state of the sub splits.

**To Reproduce**
1. Open splits with subsplits
2. Collapse splits (e.g. Desert and Winter)
3. Hit "Show PBs Only" button
4. Watch as splits uncollapse

**Expected behavior**
Either whatever state each split is in should save (collapsed vs no collapsed) or the default state should be collapsed instead of uncollapsed.

**Comment by AJ213** [comment]
Another issue is that the scrollbar resets to the top too. This is likely not really a "bug" but it would be preferred if whatever state the table was in was saved and not changed when changing the graph.

**Comment by noahkra** [comment]
I guess this could've been labeled under "lazy programming". Fixed in next version. (also the scrollbar resetting was part of the lazy programming, so I guess part of the bug too)
