### ISSUE TITLE
TypeError: Cannot read property 'substring' of undefined

### ISSUE THREAD

**Issue by AJ213** [noahkra/SplitsAnalyser#12]
**Describe the bug**
It seems the program is unable to read my Any% splits properly

**To Reproduce**
1. Open my Clustertruck Any% splits or anything similar to it
2. Cry when the error pops up

**Expected behavior**
Any% splits should display the graph information, or at least display as much as it can with the information it can read besides "NaN". That or the program should explain to the user what they can do to fix the issue on their side if it is a user-related problem or tell them why the program can't read the file.

**Screenshots**
![NaN](https://user-images.githubusercontent.com/16274000/77001196-c3005f80-6916-11ea-8812-2fa41cc0118d.PNG)

**Additional context**
If you need any% splits I can send them to you over discord again just ask. However, I can't post them here because GitHub doesn't like the filetype.

**Comment by noahkra** [comment]
Problem identified: program doesn't support custom properties because that causes the splittime variable to become an array.

**Comment by noahkra** [comment]
Issue has been fixed in the next version
