### ISSUE TITLE
Empty Splits Should Give a Specific Proper Error

### ISSUE THREAD

**Issue by AJ213** [noahkra/SplitsAnalyser#13]
**Describe the feature you'd like to request.**
When opening empty splits, you will get the typical "TypeError: Cannot read property 'substring' of undefined." There should be a custom error notifying the user that the program isn't working because the splits are empty. (You could also call them dumb, but that is mean, all users are assumed to be dumb haha).

**Give reasoning on why this feature is needed.**
Specific errors give the user a better understanding of what they did wrong and will give them a better idea of if they should post an error or not to the GitHub. The more essential information the user the less they need to ask online what they did wrong and the more time is saved on both sides.

**Additional context**
You *could* also have the table and graph display something special or just display the text "Empty Splits" instead of an empty table and graph. It would just make the program look more professional is all. Not really necessary.

**Comment by noahkra** [comment]
Defining errors that give the user more context of what's wrong is a good idea.

**Comment by noahkra** [comment]
Empty split error has been added, more will be added over time when needed.
