### ISSUE TITLE
Default Opening Last Split/Game

### ISSUE THREAD

**Issue by AJ213** [noahkra/SplitsAnalyser#14]
**Describe the feature you'd like to request.**
When opening the program or open a specific game, the last opened game/split should be opened for ease of use of the program. This also makes it easier for people to check the same one split they always check over and over.

**Give reasoning on why this feature is needed.**
1. Makes it easier to use the program for the given purpose stated above
2. Shows the pretty graphs and information instantly when you open the program or a game

**Additional context**
Sad emptiness
![emptyness](https://user-images.githubusercontent.com/16274000/77002852-74a09000-6919-11ea-9c67-a4df491edfff.PNG)
If I had to think how you could do this, you could have each game have a default split they open depending on the last one the user opened, and you could also have a default game the program opens depending on the last one the user has used. If you need more context or information on what I am talking about I can provide more context over discord.

**Comment by noahkra** [comment]
This is a good idea, I've been thinking of adding a currentstate storage file and I guess this is a good opportunity

**Comment by noahkra** [comment]
Game menu and split menu focus will now be saved in the new programstate file. will be in next release
