### ISSUE TITLE
When Open A Split, The Split (and game of course) Should Automatically Be Opened

### ISSUE THREAD

**Issue by AJ213** [noahkra/SplitsAnalyser#15]
**Describe the feature you'd like to request.**
Currently, when you load a new split the program doesn't react and it just adds mysteriously. Instead, the program should force open that game and split. I am not sure how this would look though when opening multiple splits at once, but for now, it would be wise to forbid users to open another split while one is loading in.

**Give reasoning on why this feature is needed.**
1. The program feels unresponsive when opening a split
2. If a user is opening a split, they probably want to see it
3. It makes it easier to use the program and faster (we are speedrunners here, we got to speedrun analyzing).

**Additional context**
As usual, ask me for additional context or info if you are confused.

**Comment by noahkra** [comment]
This should be easy enough, just put the split/menu select function at the bottom of the import function.

**Comment by noahkra** [comment]
Implemented, will be in next release
