### ISSUE TITLE
Ability To Open Multiple Splits

### ISSUE THREAD

**Issue by AJ213** [noahkra/SplitsAnalyser#16]
**Describe the feature you'd like to request.**
When opening splits, the user should be able to select multiple split files at once and open them through doing things like holding shift/control and selecting.

**Give reasoning on why this feature is needed.**
1. Easier to import dozens of splits at once if needed
2. Other programs typically have this feature where it makes sense.

**Additional context**
As usual, if you need additional information ask me over discord and I will update this section for you.

**Comment by noahkra** [comment]
Implemented, will be in next release
