### ISSUE TITLE
Drag and Drop Splits Files

### ISSUE THREAD

**Issue by AJ213** [noahkra/SplitsAnalyser#17]
**Describe the feature you'd like to request.**
I think it would be cool if I could drag and drop splits files into the program like how you can with other programs (like osu or video files for youtube)

**Give reasoning on why this feature is needed.**
1. Another way to put in files to the program
2. It is standard in some cool programs
3. It's flashy and cool
4. One could argue it would make the Analysis Any% speedrun faster

**Additional context**
Ask on discord if you need more information as always.

**Comment by noahkra** [comment]
Added
