### ISSUE TITLE
Save Window Location and Size

### ISSUE THREAD

**Issue by AJ213** [noahkra/SplitsAnalyser#18]
**Describe the feature you'd like to request.**
The program should have its location (be it on another monitor or not) and its size (be it windowed bigger or fullscreen) saved and should open however it was closed.

**Give reasoning on why this feature is needed.**
1. Saves time having people readjust the program every time they launch it (would save time in Anaylsis any%)
2. Kind of nice for streamers who have a specific setup for their programs and want to show the SplitsAnalyser program on stream

**Additional context**
Ronins old autosplitter did this too. If you need further context as always ask.

**Comment by noahkra** [comment]
Implemented. Not sure if I'm happy with the way I've done it yet, time will tell..
