### ISSUE TITLE
Odd Table Allignment?

### ISSUE THREAD

**Issue by AJ213** [noahkra/SplitsAnalyser#19]
**Describe the feature you'd like to request.**
Despite the title is a question, the feature requested here is for the table to not have "odd" formatting. I believe the "Segment" data is left-aligned in the table (not the header, the data), while the rest of the data (e.g. the Best Segment Data) are right-aligned to the header. What also might help is a table title, but this might be unnecessary and you might have to do testing on that.

**Give reasoning on why this feature is needed.**
The table just looks kind of jank right now, especially if there are sub-splits involved.

**Additional context**
![Table example](https://user-images.githubusercontent.com/16274000/77015633-94907d80-6932-11ea-8fad-ce6d2d1804fe.PNG)
Example of the allignment

**Comment by AJ213** [comment]
I could be mistaken though, this could be standard table alignment design. Maybe adding vertical lines might fix it appearing odd.

**Comment by noahkra** [comment]
The table is made according to Material design spec, which states text should be left aligned and numbers right aligned. No vertical lines. 

I'll take a look at it to see if I can make it look better than it does currently by limiting the width of the columns.

**Comment by noahkra** [comment]
Turns out I didn't realise the headers of the right aligned numbers should also be right aligned.. Oops. Fixed.

![image](https://user-images.githubusercontent.com/6217745/77017230-312a3e00-697a-11ea-9f0d-b0d7b95932a5.png)
