### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by AJ213** [noahkra/SplitsAnalyser#23]
**Describe the feature you'd like to request.**
A lot of features that would be requested require a settings system to be implemented because not every feature users would want universally. A way to implement this would be to have a simple settings tab on the window and/or to have small settings (Like "Only PBs") buttons near the graph/table (for their respective settings).

**Give reasoning on why this feature is needed.**
1. Settings would give the user more freedom
2. Settings would give you more freedom on development
3. Most future features require a settings system to function (like themes)

**Additional context**
As usual, nothing more to say unless you have questions for me over discord. However, I do think a good way to organize settings would be to have it something like
1. General Settings
2. Table Settings
3. Graph Settings
4. Theme
5. Preferences (?)

**Comment by noahkra** [comment]
*sigh* I guess it was gonna have to happen eventually

**Comment by noahkra** [comment]
um added? it's still empty tho
