### ISSUE TITLE
Rename 'Unnamed' Title For Splits

### ISSUE THREAD

**Issue by AJ213** [noahkra/SplitsAnalyser#25]
**Describe the feature you'd like to request.**
You were probably expecting this to be requested eventually, but I believe now might be a good time to allow users to rename splits files from "unnamed" so we can deal with the issues it might give later on.

**Give reasoning on why this feature is needed.**
1. It gives me severe brain damage when I see that I can't rename the splits files and they are just called "unnamed"
2. More customization
3. You can also just remove the unnamed text and I wouldn't care too much either in the short term. (wait, wasn't I supposed to argue for the feature?)

**Additional context**
Obligatory "ask in discord" for additional context sentence.

**Comment by noahkra** [comment]
Clicking on the split name will now allow you to rename them, blah blah next update
