### ISSUE TITLE
Fullscreen Status Not Saved On Application Closure

### ISSUE THREAD

**Issue by AJ213** [noahkra/SplitsAnalyser#26]
**Describe the bug**
When closing the application, it doesn't save if the program is fullscreen or not. Meaning that when the application is reopened it won't be in fullscreen like it was when it was closed.

**To Reproduce**
1. Open program
2. Fullscreen program
3. Close program
4. Open again for it to not be in fullscreen

**Expected behavior**
Fullscreen status should stay even if the program is closed.

**Additional context**
DM me if you have a lust for additional context.

**Comment by noahkra** [comment]
Fixed.
