### ISSUE TITLE
Opening Game Should Open Last Opened Split File

### ISSUE THREAD

**Issue by AJ213** [noahkra/SplitsAnalyser#27]
**Describe the feature you'd like to request.**
Currently, when selected a game in the program no split file is automatically selected and there is just emptiness. I believe we should show the beauty of the program as much as possible. Therefore, the program should open the last opened split file for that individual game.

**Give reasoning on why this feature is needed.**
1. Submitting to the aesthetic gods
2. Improves Analysis Any% time
3. Overall consistency and useability improvement.

**Additional context**
Ask on discord

**Comment by noahkra** [comment]
Works, don't touch it.
