### ISSUE TITLE
Tooltips Everywhere

### ISSUE THREAD

**Issue by AJ213** [noahkra/SplitsAnalyser#29]
**Describe the feature you'd like to request.**
The program should have tooltips almost everywhere in most elements. Be it text, buttons, or headers. Tooltips provide the user with the additional info they might want and save them having to look things up or ask.

**Give reasoning on why this feature is needed.**
1. Saves the user time and provides an alternative method of giving them information
2. Makes the program overall look more professional
3. Saves you time from receiving answering pointless questions like "What does SOB mean?"

**Additional context**
If you need help with what these tooltips would say, ask on discord.

**Comment by noahkra** [comment]
May have overdone it a bit but... added.
