### ISSUE TITLE
Collapse Subsplits by Split

### ISSUE THREAD

**Issue by AJ213** [noahkra/SplitsAnalyser#3]
When using subsplits, there should be a way to collapse a split to not show the subsplits. For example, for Clustertruck you would collapse the "Desert" split to not show all 10 of the subsplits.

This feature would make it easier to navigate splits

If you want an example of this, Discord collapses text channels through using categories. In the Clustertruck Speedrunning Discord, the category is the Clustertruck Speedrunning category and the text channels are like #speedrunning or #development. You can choose to collapse (or hide) these text channels be clicking the category.

**Comment by noahkra** [comment]
This one will take some work but it'll be in the next release (probably) :)

**Comment by noahkra** [comment]
Implemented! Will be in the next release.
