### ISSUE TITLE
PB and Average PB Are Not Technically PB and Average PB (Program Unusable)

### ISSUE THREAD

**Issue by AJ213** [noahkra/SplitsAnalyser#31]
**Describe the bug**
When I saw that the PB line wasn't actually my PBs (it was showing completed runs) I screamed and started to shake and cry in my chair. I have never felt such emotional pain and wish the program didn't mislead me in such a way.

**To Reproduce**
1. Open Splits file
2. Look at the horror that is the misleading graph key
3. Cry

**Expected behavior**
I am not exactly sure what the graph is showing in the "Show All" mode, but I think the key should show maybe "Run Time" and "Average Run Time" instead of "PB" and "Average PB". This should actually work for both modes too if you don't want to put in the effort to make the key different depending on the mode.

**Additional context**
To provide additional pain, ask for additional context.

**Comment by noahkra** [comment]
This was fixed before you even submitted this. SMH

Get with the times boomer.

**Comment by noahkra** [comment]
Also apologies for the wasted effort you put into submitting this issue
