### ISSUE TITLE
Additional Hotkeys To Control Program

### ISSUE THREAD

**Issue by AJ213** [noahkra/SplitsAnalyser#32]
**Describe the feature you'd like to request.**
I believe the program should use hotkeys wherever it makes sense. Some examples of some good, standard hotkeys would be splits navigation through arrow keys (maybe side arrows can open splits file and/or switch the navigation to be on the games), Enter to open currently selected splits, F2 to rename, Delete to delete splits and more. I don't other common hotkeys since I normally don't use them, but I do however use F2 and Delete a lot in other programs.

**Give reasoning on why this feature is needed.**
1. Hotkeys improve Analysis Any% time
2. Overall useability and professionalism of the program.

**Additional context**
Be sure to leave a like, and if you want additional context, be sure to ask in the comment section below.

**Comment by noahkra** [comment]
Anything to improve Analysis Any% times

**Comment by noahkra** [comment]
Added :)
