### ISSUE TITLE
Table Headers Always Visible

### ISSUE THREAD

**Issue by AJ213** [noahkra/SplitsAnalyser#33]
**Describe the feature you'd like to request.**
Let's assume the splits file is very long and you want to look at a segment that is near the bottom of the list, the table headers will disappear so (if you forget) you would have to scroll to the top again to view the header. One way to solve this issue would be to have the headers always visible and just kind of "stick" to the top of the window when the table is scrolled down.

**Give reasoning on why this feature is needed.**
1. It makes it quicker to view certain data because you don't need to scroll the table back up and down again.
2. Fewer headaches from overall basic confusion.

**Additional context**
Ask below for further context. If you want an example of this, take the youtube search bar or overall bar on youtube. The bar will always be on the top of the window no matter what even if you scroll down to view the comments.

**Comment by noahkra** [comment]
Added
