### ISSUE TITLE
Renaming Splits to Nothing Makes It Impossible to Rename Again Without Deleting

### ISSUE THREAD

**Issue by AJ213** [noahkra/SplitsAnalyser#35]
**Describe the bug**
Literally what the title says. Just try reproducing it.

**To Reproduce**
1. Rename the split file to nothing or to a bunch of space (which is also nothing really)
2. Try to change the name again
3. :(

**Expected behavior**
I would suggest having the rename box have a minimum size. Even if you make empty names default to something else instead, you would still have an issue where small names would be difficult to rename (and you could accidentally delete the splits file instead, the trash can should probably not be near the rename field). Maybe you could have an underline where the text field is and have that underline be a minimum size and expand depending on how long the title is.

**Additional context**
An example of the last thing mentioned in expected behavior would be these three examples
a) Renaming to nothing => _______
b) Renaming to Hi (pretend Hi is also underlined) => Hi_____
c) Renaming to "Super Awesome Any% Split" (also pretend this is underlined) => Super Awesome Any% Split__

Note how c) does not have as much underline after it as b). This is because b) is really short and difficult to click on, therefore it has a lot of additional underlines to compensate for that. Hopefully, this suggestion is clear, if not ask.

**Comment by noahkra** [comment]
Added min of 3 non null characters for split names. I think this solves the problem
