### ISSUE TITLE
Renaming A Split Really Long Looks Weird

### ISSUE THREAD

**Issue by AJ213** [noahkra/SplitsAnalyser#36]
**Describe the bug**
If you rename a split file to be a really long name, it kind of goes out of control on the UI and expands across it.

**To Reproduce**
1. Rename split file to something really long like "OOOOOOOOOOOOOOOOOOOOOOOOOOOO"
2. Notice it looking funky

**Expected behavior**
When the name is too long, have the last bit appear as "OOOOO..." instead of having the name extend past the box its inside. This is what discord does too for a lot of text.

**Screenshots**
![yesss](https://user-images.githubusercontent.com/16274000/77513092-8b6f4700-6e31-11ea-88c8-ae971dfacd8a.PNG)

**Additional context**
 Null

**Comment by noahkra** [comment]
Added a text ellipsis for strings longer than 150px. Also added a min of 3 characters for a name to be valid.
