### ISSUE TITLE
Clicking Away While Renaming A Split Should Also Confirm it

### ISSUE THREAD

**Issue by AJ213** [noahkra/SplitsAnalyser#37]
**Describe the feature you'd like to request.**
In windows file explorer when you rename a file and click somewhere else it confirms the rename. The rename feature for splits should also do the same.

**Give reasoning on why this feature is needed.**
1. Makes it faster to rename for people who are used to doing it like this
2. Overall common functionality that is expected
3. I keep trying to do it and failing. Every time I try and fail to do this I die in the inside.

**Additional context**
Nill, just ask or mess around with how renaming works in windows file explorer.

**Comment by noahkra** [comment]
shit I was hoping nobody would suggest this

**Comment by noahkra** [comment]
Okay added
