### ISSUE TITLE
TypeError on split file

### ISSUE THREAD

**Issue by Happyrobot33** [noahkra/SplitsAnalyser#38]
Tried to open one of my split files and got this error
`Error: TypeError: Cannot read property 'substring' of undefined`

[Splits File](https://github.com/noahkra/SplitsAnalyser/files/4396352/Clustertruck.-.NoAbility.Laser.zip)

**Comment by noahkra** [comment]
This is because this splits file doesn't contain any finished runs yet. I've added a custom error for when this happens.
