### ISSUE TITLE
Split Naming

### ISSUE THREAD

**Issue by Happyrobot33** [noahkra/SplitsAnalyser#39]
**Describe the feature you'd like to request.**
Name splits based on filename IE if file is named Clustertruck - NoAbility Desert, remove the game name and make it NoAbility Desert

**Give reasoning on why this feature is needed.**
Because most people already have their split files named correctly, so we can assume the name

**Comment by noahkra** [comment]
Nice suggestion. I've also removed the category from the name as that's already noted in the splits menu. Added.
