### ISSUE TITLE
Key and Title For Graph

### ISSUE THREAD

**Issue by AJ213** [noahkra/SplitsAnalyser#4]
Most graphs have labels, titles and keys to show what the graph is displaying. Normally there would be something showing what the y-axis of the graph represents and the x-axis, there would also be a title for what the graph is showing, and there should be a key on what each of the lines represents. In short, I am basically asking for the graph to be more clear on what it is showing.

This feature is needed because I don't know what each of the lines on the graph represents and some people may not know the x-axis represents attempts and such.

I am sure you can look up examples online for what I am talking about. If you need me to show you an example I can send it to you over discord.

**Comment by noahkra** [comment]
This has been implemented and will be in the next release 👍
