### ISSUE TITLE
Splash screen image doesnt load

### ISSUE THREAD

**Issue by Happyrobot33** [noahkra/SplitsAnalyser#40]
**Describe the bug**
When the splash screen shows up, it loads the missing image "Image"

**To Reproduce**
launch the program

**Expected behavior**
Show the splash screen image

**Additional context**
My OS is running off of an SSD so that might be affecting it

**Comment by noahkra** [comment]
I get this too. Problem is because I forgot to package a certain folder. Releasing patch in a sec.
