### ISSUE TITLE
Unable to Open Splits From Other Games

### ISSUE THREAD

**Issue by AJ213** [noahkra/SplitsAnalyser#45]
**Describe the bug**
If I try to open my Celeste splits or splits from any other game besides Clustertruck after receiving update v0.4.1 I get an error stating "TypeError: Cannon set property 'clustertruck' of undefined"

**To Reproduce**
1. Open splits from a game other than Clustertruck
2. Error pops up
3. Other game image will show up on the left, but you can't select it

**Expected behavior**
You should be able to see your splits from another game.

**Screenshots**
![help me](https://user-images.githubusercontent.com/16274000/81491100-d8bb4280-923e-11ea-9672-24a3cf0d6ae1.PNG)

**Additional context**
If you are unable to replicate, it is likely this is due to updating to v0.4.1 from v0.3.0. Although I don't know this for sure since I didn't program this program lol.

**Comment by AJ213** [comment]
Update: I was able to add other games after I deleted all my clustertruck splits and then re-opened the program. Now the program is working as intended after doing this. However, that doesn't mean this bug doesn't exist anymore (although, if you get like 2 other people to do this it would probably be fixed for everyone (although although, this could be a recurring bug every time you update the program to a new version))

**Comment by noahkra** [comment]
I haven't been able to recreate this yet. Gonna try installing an old version and then upgrading again.

**Comment by Happyrobot33** [comment]
cant recreate either. my SM64 splits worked fine

**Comment by noahkra** [comment]
"If one can not reproduce a bug, does it really exist?"

- Socrates
