### ISSUE TITLE
Lag When Loading Split File

### ISSUE THREAD

**Issue by AJ213** [noahkra/SplitsAnalyser#5]
When you load up a splits file there is a decent amount of lag when doing so. It is unclear to the user if their attempt to add a splits file to the program is working or not.

**To Reproduce**
1. Add a split file
2. Wait
3. Split file is added up to 30 seconds later after the action

**Expected behavior**
There should either be very little lag for a splits file to load or some indication that a splits file is loading in the program. (like maybe a loading animation or something to show that "hey, the program is busy loading in that splits file you didn't do anything wrong")

**Comment by noahkra** [comment]
Splits files shouldn't take more than a couple seconds to import unless they are really big, or your hard drive is having trouble reading the file. If this keeps up I'll have to look into it. 

I've added a loading circle next to the cursor to indicate when a splits file is being imported. Included in next release!
