### ISSUE TITLE
Add support for Different Comparisons

### ISSUE THREAD

**Issue by Happyrobot33** [noahkra/SplitsAnalyser#50]
**Describe the feature you'd like to request.**
As livesplit has 2 different comparison methods, I feel like this should be represented. somehow showing normal time and game time. would also be cool to see how much time was lost to loading in the bar graph or as a number.

**Give reasoning on why this feature is needed.**
More data and adding support to IGT for clustertruck and other games that use it.

**Comment by noahkra** [comment]
Add the moment it automatically selects which timing method to compare to, from what the splits file tells it is the main timing method for the game, but yea a manual toggle would be a good addition.

**Comment by noahkra** [comment]
Fixed in v0.5.0 :)
