### ISSUE TITLE
"A Javascript error occurred in the main process" error when starting program

### ISSUE THREAD

**Issue by brododragon** [noahkra/SplitsAnalyser#54]
When I start the program, I get an error. Error: 
![image](https://user-images.githubusercontent.com/67079110/116733421-1538fe80-a9ba-11eb-8285-9e7db58b3aee.png)

**Comment by noahkra** [comment]
Hi there! Thanks for using the application!

The issue you're having is a known one and will be fixed when I get around to releasing the next version. For now there's a workaround that will fix the problem:

1. Install [version 0.3.0](https://github.com/noahkra/SplitsAnalyser/releases/tag/v0.3.0)
2. Launch the application and drag the window around a bit (this creates the file needed for the latest version to not error anymore).
3. Install the latest version again

If this didn't work of if you have any questions feel free to reply :)

Closed the issue for now.
