### ISSUE TITLE
Installer .exe detected as a trojan by Windows Defender

### ISSUE THREAD

**Issue by w-biggs** [noahkra/SplitsAnalyser#55]
**Describe the bug**
When downloaded, Windows quarantines the file and says it contains a trojan - Win32/Bulta!rfn

**To Reproduce**
1. Download the .exe release on a Windows machine

**Expected behavior**
Should not be detected as a trojan.

**Additional context**
This apparently is a somewhat common false positive caused by downloading additional dependencies at runtime(?) so that might be the case here too.

**Comment by noahkra** [comment]
Actually fixed this (found the solution working on something else). 

Ended up downgrading electron-builder so it uses an older binary that isn't flagged as a false positive.

:)
